// Code generated by cmd/genfonts. DO NOT EDIT.

// Copyright (c) 2026 the go-opentype/fonts authors. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license that can be
// found in the LICENSE file at the root of this repository.

package fonts

// generated lists every family cmd/genfonts has successfully ingested from
// github.com/google/fonts. Re-run `go run ./cmd/genfonts` from the module
// root to regenerate this file.
var generated = []Family{
	{Name: "Arimo", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/arimo"},
	{Name: "Bitter", Kind: KindSerif, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/bitter"},
	{Name: "Cabin", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/cabin"},
	{Name: "Cousine", Kind: KindMono, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/cousine"},
	{Name: "DM Sans", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/dmsans"},
	{Name: "Fira Code", Kind: KindMono, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/firacode"},
	{Name: "Fira Sans", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/firasans"},
	{Name: "IBM Plex Mono", Kind: KindMono, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/ibmplexmono"},
	{Name: "IBM Plex Sans", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/ibmplexsans"},
	{Name: "Inconsolata", Kind: KindMono, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/inconsolata"},
	{Name: "Karla", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/karla"},
	{Name: "Lato", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/lato"},
	{Name: "Manrope", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/manrope"},
	{Name: "Montserrat", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/montserrat"},
	{Name: "Mulish", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/mulish"},
	{Name: "Noto Emoji", Kind: KindEmoji, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/notoemoji"},
	{Name: "Noto Sans", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/notosans"},
	{Name: "Noto Sans Arabic", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/notosansarabic"},
	{Name: "Noto Sans Armenian", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/notosansarmenian"},
	{Name: "Noto Sans Devanagari", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/notosansdevanagari"},
	{Name: "Noto Sans Egyptian Hieroglyphs", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/notosansegyptianhieroglyphs"},
	{Name: "Noto Sans Georgian", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/notosansgeorgian"},
	{Name: "Noto Sans Hebrew", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/notosanshebrew"},
	{Name: "Noto Sans JP", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/notosansjp"},
	{Name: "Noto Sans KR", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/notosanskr"},
	{Name: "Noto Sans SC", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/notosanssc"},
	{Name: "Noto Sans Thai", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/notosansthai"},
	{Name: "Nunito", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/nunito"},
	{Name: "Nunito Sans", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/nunitosans"},
	{Name: "Open Sans", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/opensans"},
	{Name: "PT Sans", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/ptsans"},
	{Name: "Playfair Display", Kind: KindSerif, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/playfairdisplay"},
	{Name: "Poppins", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/poppins"},
	{Name: "Roboto", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/roboto"},
	{Name: "Roboto Mono", Kind: KindMono, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/robotomono"},
	{Name: "Rubik", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/rubik"},
	{Name: "Source Code Pro", Kind: KindMono, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/sourcecodepro"},
	{Name: "Source Sans 3", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/sourcesans3"},
	{Name: "Space Mono", Kind: KindMono, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/spacemono"},
	{Name: "Titillium Web", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/titilliumweb"},
	{Name: "Work Sans", Kind: KindSans, License: "OFL-1.1", ImportPath: "github.com/go-opentype/fonts/worksans"},
}
