// Code generated by cmd/genfonts. DO NOT EDIT.

// Copyright (c) 2026 the go-opentype/fonts authors. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license that can be
// found in the LICENSE file at the root of this repository.

// Package firasans embeds Fira Sans.
//
// License: OFL-1.1. Copyright (c) 2012-2015, The Mozilla Foundation and Telefonica S.A.
// Upstream: https://github.com/google/fonts/tree/main/ofl/firasans
//
// Importing this package links only Fira Sans into your binary. No other
// bundled family is compiled in unless you import its package too.
package firasans

import _ "embed" // for the //go:embed directive below

// TTF holds the raw TrueType bytes of Fira Sans, ready for opentype.Parse.
//
//go:embed firasans.ttf
var TTF []byte
