// Code generated by cmd/genfonts. DO NOT EDIT.

// Copyright (c) 2026 the go-opentype/fonts authors. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license that can be
// found in the LICENSE file at the root of this repository.

// Package notosansegyptianhieroglyphs embeds Noto Sans Egyptian Hieroglyphs.
//
// License: OFL-1.1. Copyright 2022 The Noto Project Authors (https://github.com/notofonts/egyptian-hieroglyphs)
// Upstream: https://github.com/google/fonts/tree/main/ofl/notosansegyptianhieroglyphs
//
// Importing this package links only Noto Sans Egyptian Hieroglyphs into your binary. No other
// bundled family is compiled in unless you import its package too.
package notosansegyptianhieroglyphs

import _ "embed" // for the //go:embed directive below

// TTF holds the raw TrueType bytes of Noto Sans Egyptian Hieroglyphs, ready for opentype.Parse.
//
//go:embed notosansegyptianhieroglyphs.ttf
var TTF []byte
