// Code generated by cmd/genfonts. DO NOT EDIT.

// Copyright (c) 2026 the go-opentype/fonts authors. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license that can be
// found in the LICENSE file at the root of this repository.

// Package cousine embeds Cousine.
//
// License: OFL-1.1. Copyright 2026 The Cousine Project Authors (https://github.com/googlefonts/cousine)
// Upstream: https://github.com/google/fonts/tree/main/ofl/cousine
//
// Importing this package links only Cousine into your binary. No other
// bundled family is compiled in unless you import its package too.
package cousine

import _ "embed" // for the //go:embed directive below

// TTF holds the raw TrueType bytes of Cousine, ready for opentype.Parse.
//
//go:embed cousine.ttf
var TTF []byte

// Bold holds the raw TrueType bytes of the bold face.
//
//go:embed cousine-bold.ttf
var Bold []byte

// Italic holds the raw TrueType bytes of the italic face.
//
//go:embed cousine-italic.ttf
var Italic []byte

// BoldItalic holds the raw TrueType bytes of the bold italic face.
//
//go:embed cousine-bolditalic.ttf
var BoldItalic []byte
