// Code generated by cmd/genfonts. DO NOT EDIT.

// Copyright (c) 2026 the go-opentype/fonts authors. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license that can be
// found in the LICENSE file at the root of this repository.

package cousine

import (
	"testing"

	"github.com/go-opentype/opentype"
)

// TestParse proves TTF loads through go-opentype and has at least one
// glyph, on every CI run.
func TestParse(t *testing.T) {
	f, err := opentype.Parse(TTF)
	if err != nil {
		t.Fatalf("opentype.Parse: %v", err)
	}
	if f.NumGlyphs() <= 0 {
		t.Fatalf("NumGlyphs() = %d, want > 0", f.NumGlyphs())
	}
}

// TestEveryFaceParses proves the other faces bundled beside TTF load too. A
// face that is embedded and broken is worse than one that is absent: nothing
// reads it until a document asks for that weight, and then it fails where a
// page is being drawn rather than here.
func TestEveryFaceParses(t *testing.T) {
	for _, c := range []struct {
		name string
		ttf  []byte
	}{
		{"Bold", Bold},
		{"Italic", Italic},
		{"BoldItalic", BoldItalic},
	} {
		f, err := opentype.Parse(c.ttf)
		if err != nil {
			t.Errorf("%s: opentype.Parse: %v", c.name, err)
			continue
		}
		if f.NumGlyphs() <= 0 {
			t.Errorf("%s: NumGlyphs() = %d, want > 0", c.name, f.NumGlyphs())
		}
	}
}
