// Code generated by cmd/genfonts. DO NOT EDIT.

// Copyright (c) 2026 the go-opentype/fonts authors. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license that can be
// found in the LICENSE file at the root of this repository.

// Package sourcesans3 embeds Source Sans 3, a variable font upstream (bundled at its default master).
//
// License: OFL-1.1. Copyright 2010-2020 Adobe (http://www.adobe.com/), with Reserved Font Name 'Source'. All Rights Reserved. Source is a trademark of Adobe in the United States and/or other countries.
// Upstream: https://github.com/google/fonts/tree/main/ofl/sourcesans3
//
// Source Sans 3 is a variable font upstream; the bundled .ttf is pinned at its
// default master (static instance). go-opentype has no variable-font
// support, so it always renders that default instance — OpenType
// Variations axes are not applied.
//
// Importing this package links only Source Sans 3 into your binary. No other
// bundled family is compiled in unless you import its package too.
package sourcesans3

import _ "embed" // for the //go:embed directive below

// TTF holds the raw TrueType bytes of Source Sans 3, ready for opentype.Parse.
//
//go:embed sourcesans3.ttf
var TTF []byte
