// Code generated by cmd/genfonts. DO NOT EDIT.

// Copyright (c) 2026 the go-opentype/fonts authors. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license that can be
// found in the LICENSE file at the root of this repository.

// Package tinos embeds Tinos.
//
// License: OFL-1.1. Copyright 2026 The Tinos Project Authors (https://github.com/googlefonts/tinos)
// Upstream: https://github.com/google/fonts/tree/main/ofl/tinos
//
// Importing this package links only Tinos into your binary. No other
// bundled family is compiled in unless you import its package too.
package tinos

import _ "embed" // for the //go:embed directive below

// TTF holds the raw TrueType bytes of Tinos, ready for opentype.Parse.
//
//go:embed tinos.ttf
var TTF []byte
