// Code generated by cmd/genfonts. DO NOT EDIT.

// Copyright (c) 2026 the go-opentype/fonts authors. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license that can be
// found in the LICENSE file at the root of this repository.

// Package ibmplexsans embeds IBM Plex Sans, a variable font upstream (bundled at its default master).
//
// License: OFL-1.1. Copyright © 2017 IBM Corp. with Reserved Font Name "Plex"
// Upstream: https://github.com/google/fonts/tree/main/ofl/ibmplexsans
//
// IBM Plex Sans is a variable font upstream; the bundled .ttf is pinned at its
// default master (static instance). go-opentype has no variable-font
// support, so it always renders that default instance — OpenType
// Variations axes are not applied.
//
// Importing this package links only IBM Plex Sans into your binary. No other
// bundled family is compiled in unless you import its package too.
package ibmplexsans

import _ "embed" // for the //go:embed directive below

// TTF holds the raw TrueType bytes of IBM Plex Sans, ready for opentype.Parse.
//
//go:embed ibmplexsans.ttf
var TTF []byte
