// Code generated by cmd/genfonts. DO NOT EDIT.

// Copyright (c) 2026 the go-opentype/fonts authors. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license that can be
// found in the LICENSE file at the root of this repository.

// Package inconsolata embeds Inconsolata.
//
// License: OFL-1.1. Copyright 2006 The Inconsolata Project Authors
// Upstream: https://github.com/google/fonts/tree/main/ofl/inconsolata
//
// Importing this package links only Inconsolata into your binary. No other
// bundled family is compiled in unless you import its package too.
package inconsolata

import _ "embed" // for the //go:embed directive below

// TTF holds the raw TrueType bytes of Inconsolata, ready for opentype.Parse.
//
//go:embed inconsolata.ttf
var TTF []byte
