// Code generated by cmd/genfonts. DO NOT EDIT.

// Copyright (c) 2026 the go-opentype/fonts authors. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license that can be
// found in the LICENSE file at the root of this repository.

// Package sourcecodepro embeds Source Code Pro, a variable font upstream (bundled at its default master).
//
// License: OFL-1.1. Copyright 2010, 2012 Adobe Systems Incorporated (http://www.adobe.com/), with Reserved Font Name 'Source'. All Rights Reserved. Source is a trademark of Adobe Systems Incorporated in the United States and/or other countries.
// Upstream: https://github.com/google/fonts/tree/main/ofl/sourcecodepro
//
// Source Code Pro is a variable font upstream; the bundled .ttf is pinned at its
// default master (static instance). go-opentype has no variable-font
// support, so it always renders that default instance — OpenType
// Variations axes are not applied.
//
// Importing this package links only Source Code Pro into your binary. No other
// bundled family is compiled in unless you import its package too.
package sourcecodepro

import _ "embed" // for the //go:embed directive below

// TTF holds the raw TrueType bytes of Source Code Pro, ready for opentype.Parse.
//
//go:embed sourcecodepro.ttf
var TTF []byte
