// Code generated by cmd/genfonts. DO NOT EDIT.

// Copyright (c) 2026 the go-opentype/fonts authors. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license that can be
// found in the LICENSE file at the root of this repository.

package notosanssc

import (
	"testing"

	"github.com/go-opentype/opentype"
)

// TestParse proves TTF loads through go-opentype and has at least one
// glyph, on every CI run.
func TestParse(t *testing.T) {
	f, err := opentype.Parse(TTF)
	if err != nil {
		t.Fatalf("opentype.Parse: %v", err)
	}
	if f.NumGlyphs() <= 0 {
		t.Fatalf("NumGlyphs() = %d, want > 0", f.NumGlyphs())
	}
}

// TestRepresentativeGlyph proves TTF maps and rasterises 中 (U+4E2D),
// a rune this family's script exists to cover — stronger evidence than
// TestParse's NumGlyphs() check alone.
func TestRepresentativeGlyph(t *testing.T) {
	f, err := opentype.Parse(TTF)
	if err != nil {
		t.Fatalf("opentype.Parse: %v", err)
	}
	const r = '中'
	face := f.NewFace(64)
	bounds, mask, _, advance, ok := face.GlyphMask(r, 0, 0)
	if !ok {
		t.Fatalf("GlyphMask(%q): rune not mapped by cmap, or corrupt outline", r)
	}
	if mask == nil {
		t.Fatalf("GlyphMask(%q): want a non-nil mask (drawn ink), got nil", r)
	}
	if bounds.Empty() {
		t.Errorf("GlyphMask(%q) bounds is empty, want a drawn glyph", r)
	}
	if advance <= 0 {
		t.Errorf("GlyphMask(%q) advance = %d, want > 0", r, advance)
	}
}
