// Code generated by cmd/genfonts. DO NOT EDIT.

// Copyright (c) 2026 the go-opentype/fonts authors. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license that can be
// found in the LICENSE file at the root of this repository.

// Package spacemono embeds Space Mono.
//
// License: OFL-1.1. Copyright 2016 The Space Mono Project Authors (https://github.com/googlefonts/spacemono)
// Upstream: https://github.com/google/fonts/tree/main/ofl/spacemono
//
// Importing this package links only Space Mono into your binary. No other
// bundled family is compiled in unless you import its package too.
package spacemono

import _ "embed" // for the //go:embed directive below

// TTF holds the raw TrueType bytes of Space Mono, ready for opentype.Parse.
//
//go:embed spacemono.ttf
var TTF []byte
