// Code generated by cmd/genfonts. DO NOT EDIT.

// Copyright (c) 2026 the go-opentype/fonts authors. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license that can be
// found in the LICENSE file at the root of this repository.

// Package ptsans embeds PT Sans.
//
// License: OFL-1.1. Copyright Holder. This restriction only applies to the primary font name as
// Upstream: https://github.com/google/fonts/tree/main/ofl/ptsans
//
// Importing this package links only PT Sans into your binary. No other
// bundled family is compiled in unless you import its package too.
package ptsans

import _ "embed" // for the //go:embed directive below

// TTF holds the raw TrueType bytes of PT Sans, ready for opentype.Parse.
//
//go:embed ptsans.ttf
var TTF []byte
