// Code generated by cmd/genfonts. DO NOT EDIT.

// Copyright (c) 2026 the go-opentype/fonts authors. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license that can be
// found in the LICENSE file at the root of this repository.

// Package arimo embeds Arimo, a variable font upstream (bundled at its default master).
//
// License: OFL-1.1. Copyright 2026 The Arimo Project Authors (https://github.com/googlefonts/arimo)
// Upstream: https://github.com/google/fonts/tree/main/ofl/arimo
//
// Arimo is a variable font upstream and the bundled arimo.ttf is that
// variable file. Face returns its default master; Font.Instance bakes any
// other point on its axes into a static font.
//
// Importing this package links only Arimo into your binary. No other
// bundled family is compiled in unless you import its package too.
package arimo

import _ "embed" // for the //go:embed directive below

// TTF holds the raw TrueType bytes of Arimo, ready for opentype.Parse.
//
//go:embed arimo.ttf
var TTF []byte

// Bold holds the raw TrueType bytes of the bold face: a static
// instance baked at wght 700 out of Arimo[wght].ttf, since upstream ships no file
// for this weight, only the axis it sits on.
//
//go:embed arimo-bold.ttf
var Bold []byte

// Italic holds the raw TrueType bytes of the italic face.
//
//go:embed arimo-italic.ttf
var Italic []byte

// BoldItalic holds the raw TrueType bytes of the bold italic face: a static
// instance baked at wght 700 out of Arimo-Italic[wght].ttf, since upstream ships no file
// for this weight, only the axis it sits on.
//
//go:embed arimo-bolditalic.ttf
var BoldItalic []byte
