// Code generated by cmd/genfonts. DO NOT EDIT.

// Copyright (c) 2026 the go-opentype/fonts authors. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license that can be
// found in the LICENSE file at the root of this repository.

// Package ibmplexmono embeds IBM Plex Mono.
//
// License: OFL-1.1. Copyright © 2017 IBM Corp. with Reserved Font Name "Plex"
// Upstream: https://github.com/google/fonts/tree/main/ofl/ibmplexmono
//
// Importing this package links only IBM Plex Mono into your binary. No other
// bundled family is compiled in unless you import its package too.
package ibmplexmono

import _ "embed" // for the //go:embed directive below

// TTF holds the raw TrueType bytes of IBM Plex Mono, ready for opentype.Parse.
//
//go:embed ibmplexmono.ttf
var TTF []byte
