// Copyright (c) 2026 the go-opentype/fonts authors. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license that can be
// found in the LICENSE file at the root of this repository.

// This file is hand-written and is NOT regenerated by cmd/genfonts: it asserts
// the properties that make this particular family usable as a fallback, which
// the generated smoke tests do not express.

package notoemoji

import (
	"testing"

	"github.com/go-opentype/opentype"
)

// TestCoversCommonEmoji proves the family maps and inks a broad spread of the
// emoji a real feed actually contains — astronomical symbols, gestures, objects
// and a dingbat from the BMP as well as the Supplementary Multilingual Plane.
// One rocket (the generated TestRepresentativeGlyph) does not establish that.
func TestCoversCommonEmoji(t *testing.T) {
	f, err := opentype.Parse(TTF)
	if err != nil {
		t.Fatalf("opentype.Parse: %v", err)
	}
	face := f.NewFace(48)
	for _, r := range []rune{
		'🚀', '🌔', '🌘', '🧑', '👏', '👍', '✨', '🔥', '🗞', '⚠', '🎉', '❤',
	} {
		t.Run(string(r), func(t *testing.T) {
			if _, ok := f.GlyphIndex(r); !ok {
				t.Fatalf("U+%04X is not in the cmap", r)
			}
			bounds, mask, _, advance, ok := face.GlyphMask(r, 0, 48)
			if !ok || mask == nil {
				t.Fatalf("U+%04X did not rasterise (ok=%v, mask=%v)", r, ok, mask)
			}
			if bounds.Empty() || advance <= 0 {
				t.Fatalf("U+%04X drew nothing: bounds=%v advance=%d", r, bounds, advance)
			}
			inked := 0
			for _, p := range mask.Pix {
				if p > 0 {
					inked++
				}
			}
			if inked == 0 {
				t.Fatalf("U+%04X produced a blank mask", r)
			}
		})
	}
}

// TestCarriesNoLetters is the property that makes this family safe to chain
// LAST behind any text face: it has no letterforms in any script, so a
// first-face-that-covers-the-rune fallback can never route real words to it.
// Were that to change upstream, an emoji fallback could start shadowing text.
func TestCarriesNoLetters(t *testing.T) {
	f, err := opentype.Parse(TTF)
	if err != nil {
		t.Fatalf("opentype.Parse: %v", err)
	}
	for _, r := range []rune{'A', 'z', 'Q', 'é', 'Ç', 'Ω', 'д', '中', 'あ', '가', 'ا', 'ה', 'ก'} {
		if _, ok := f.GlyphIndex(r); ok {
			t.Errorf("U+%04X %q is mapped, but an emoji family must carry no letters "+
				"— chaining it as a fallback would shadow real text", r, r)
		}
	}
}

// TestLatinRangeIsOnlyKeycapBases pins the ONE surprise in this family's
// coverage: it does map a handful of ASCII, because "#", "*" and the digits are
// the bases of the keycap emoji sequences (0️⃣ is U+0030 U+FE0F U+20E3), and it
// maps space, © and ® for the same emoji-sequence reasons.
//
// That is harmless in a fallback chain — a text face covers all fifteen, so the
// emoji face is never consulted for them — but it is exactly the kind of overlap
// that would matter if the set grew. Pinning it makes any upstream widening
// visible in CI instead of as mysteriously wrong-looking digits.
func TestLatinRangeIsOnlyKeycapBases(t *testing.T) {
	f, err := opentype.Parse(TTF)
	if err != nil {
		t.Fatalf("opentype.Parse: %v", err)
	}
	want := map[rune]bool{
		' ': true, '#': true, '*': true, '©': true, '®': true,
		'0': true, '1': true, '2': true, '3': true, '4': true,
		'5': true, '6': true, '7': true, '8': true, '9': true,
	}
	// U+0020..U+024F: ASCII, Latin-1 Supplement, Latin Extended-A and -B.
	for r := rune(0x20); r <= 0x24F; r++ {
		_, mapped := f.GlyphIndex(r)
		if mapped != want[r] {
			t.Errorf("U+%04X %q: mapped=%v, want %v", r, r, mapped, want[r])
		}
	}
}
