// Code generated by cmd/genfonts. DO NOT EDIT.

// Copyright (c) 2026 the go-opentype/fonts authors. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license that can be
// found in the LICENSE file at the root of this repository.

// Package notosansgeorgian embeds Noto Sans Georgian, a variable font upstream (bundled at its default master).
//
// License: OFL-1.1. Copyright 2022 The Noto Project Authors (https://github.com/notofonts/georgian)
// Upstream: https://github.com/google/fonts/tree/main/ofl/notosansgeorgian
//
// Noto Sans Georgian is a variable font upstream; the bundled .ttf is pinned at its
// default master (static instance). go-opentype has no variable-font
// support, so it always renders that default instance — OpenType
// Variations axes are not applied.
//
// Importing this package links only Noto Sans Georgian into your binary. No other
// bundled family is compiled in unless you import its package too.
package notosansgeorgian

import _ "embed" // for the //go:embed directive below

// TTF holds the raw TrueType bytes of Noto Sans Georgian, ready for opentype.Parse.
//
//go:embed notosansgeorgian.ttf
var TTF []byte
