// Code generated by cmd/genfonts. DO NOT EDIT.

// Copyright (c) 2026 the go-opentype/fonts authors. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license that can be
// found in the LICENSE file at the root of this repository.

package poppins

import (
	"testing"

	"github.com/go-opentype/opentype"
)

// TestParse proves TTF loads through go-opentype and has at least one
// glyph, on every CI run.
func TestParse(t *testing.T) {
	f, err := opentype.Parse(TTF)
	if err != nil {
		t.Fatalf("opentype.Parse: %v", err)
	}
	if f.NumGlyphs() <= 0 {
		t.Fatalf("NumGlyphs() = %d, want > 0", f.NumGlyphs())
	}
}
