// Code generated by cmd/genfonts. DO NOT EDIT.

// Copyright (c) 2026 the go-opentype/fonts authors. All rights reserved.
// Use of this source code is governed by a BSD-3-Clause license that can be
// found in the LICENSE file at the root of this repository.

// Package poppins embeds Poppins.
//
// License: OFL-1.1. Copyright 2020 The Poppins Project Authors (https://github.com/itfoundry/Poppins)
// Upstream: https://github.com/google/fonts/tree/main/ofl/poppins
//
// Importing this package links only Poppins into your binary. No other
// bundled family is compiled in unless you import its package too.
package poppins

import _ "embed" // for the //go:embed directive below

// TTF holds the raw TrueType bytes of Poppins, ready for opentype.Parse.
//
//go:embed poppins.ttf
var TTF []byte
